### ISSUE TITLE
Code Chapter 3

### ISSUE THREAD

**Issue by carazza** [erykml/Python-for-Finance-Cookbook#2]
Dear Eryk,

When I run this code in jupiter notebook (chapter 3):

DEFL_DATE = date(2011, 12, 31)
df[‘dt_index’] = df.index.map(lambda x: x.to_pydatetime().date())
df[‘price_deflated’] = df.apply(lambda x: cpi.inflate(x.price,
x.dt_index,
DEFL_DATE),
axis=1)
df[[‘price’, ‘price_deflated’]].plot(title=’Gold Price (deflated)’)
plt.tight_layout()
#plt.savefig(‘images/ch3_im9.png’)
plt.show()
There is a error message:

TypeError: float() argument must be a string or a number, not ‘Period’

But, if I ran in google colab, it runs perfectly… (exactly the same code). Why?

Thanks and congrats on your book.

**Comment by erykml** [comment]
Hi! Could you please compare (and ideally paste here as well) the versions of the libraries you are using in both environments? This might help in identifying the issue.
