### ISSUE TITLE
data missing

### ISSUE THREAD

**Issue by karenjh2** [erykml/Python-for-Finance-Cookbook#3]
The file credit_card_fraud_.csv is used in your code but is not included. How can I obtain this data file? thanks.

**Comment by karenjh2** [comment]
in calculating realized volatility, 

fig, ax = plt.subplots(2, 1, sharex=True)

I get error NameError: name 'plt' is not defined

Iadded import matplotlib.pyplot as plt
which resolved error but another line is required to display graph: plt.show()

**Comment by karenjh2** [comment]
in stylized facts section, you instruct reader to download S&P500 data in the same way as you previously described in Getting Data from Yahoo Finance section. But you do not mention the symbol that should be used for S&P500. It is ^GSPC which took me a few minutes to figure out.

**Comment by karenjh2** [comment]
In stylized facts section, line fig, ax = plt.subplots(1, 2, figsize=(16, 8))
I get error  NameError: name 'plt' is not defined

**Comment by karenjh2** [comment]
in stylized return section, plotting S&P500 data you have line
ax[0].set_title('Distribution of MSFT returns'

but this is S&P500 data not MSFT data.

**Comment by karenjh2** [comment]
in stylized return section, plotting S&P500 data you have line
ax[0].set_title('Distribution of MSFT returns'

but this is S&P500 data not MSFT data.

**Comment by erykml** [comment]
Hi karenjh2, 

Please find below answers to your issues:

> The file credit_card_fraud_.csv is used in your code but is not included. How can I obtain this data file? thanks.

The file is available in the datasets directory.

> in calculating realized volatility,
> 
> fig, ax = plt.subplots(2, 1, sharex=True)
> 
> I get error NameError: name 'plt' is not defined
> 
> Iadded import matplotlib.pyplot as plt
> which resolved error but another line is required to display graph: plt.show()

> In stylized facts section, line fig, ax = plt.subplots(1, 2, figsize=(16, 8))
> I get error NameError: name 'plt' is not defined

As mentioned in the **To get the most out of this book** section: At the very beginning of each notebook (available on the book's GitHub repository), we run a few cells that import and set up plotting with matplotlib. We will not mention this later on, as this would be repetitive, so at any time, assume that matplotlib is imported.

> in stylized facts section, you instruct reader to download S&P500 data in the same way as you previously described in Getting Data from Yahoo Finance section. But you do not mention the symbol that should be used for S&P500. It is ^GSPC which took me a few minutes to figure out.

The ticker is included in the code available in the book and on GitHub.

> in stylized return section, plotting S&P500 data you have line
> ax[0].set_title('Distribution of MSFT returns'
> 
> but this is S&P500 data not MSFT data.

Good remark! Thanks for it, it is actually an oversight. The analyzed data is indeed SP500, the only places with mistakes are the plot titles. I will correct this in the Notebook available on GitHub.

Hope this helps!

Eryk
