### ISSUE TITLE
Chapter 1 Changing Frequency plot

### ISSUE THREAD

**Issue by Rookiebull32** [erykml/Python-for-Finance-Cookbook#4]
Hi Eryk, awesome book:

Barely learning python and python for finance. 
I found that the following modules are missing in Chapter 1 Changing Frequency, plotting part. 
Hope this helps newbies like myself.

import numpy as np

import matplotlib.pyplot as plt

**Comment by erykml** [comment]
Hi!

Thanks for the nice words about the book and the feedback :) Regarding plotting, it was mentioned in the **To get the most out of this book** section that: At the very beginning of each notebook (available on the book's GitHub repository), we run a few cells that import and set up plotting with matplotlib. We will not mention this later on, as this would be repetitive, so at any time, assume that matplotlib is imported.

Hope this helps!

Cheers, 
Eryk
