### ISSUE TITLE
The customized function in the Chapter 1 Notebook, def indentify_outliers(row, n_sigmas=3)

### ISSUE THREAD

**Issue by TY-Cheng** [erykml/Python-for-Finance-Cookbook#5]
Since we have listed the argument n_sigmas=3, maybe we should use it inside the function.

Thx!

![image](https://user-images.githubusercontent.com/14033617/107137702-f6424780-6949-11eb-9ee3-de4469602d1d.png)

def indentify_outliers(row, n_sigmas=3):
    '''
    Function for identifying the outliers using the 3 sigma rule. 
    The row must contain the following columns/indices: simple_rtn, mean, std.
    
    Parameters
    ----------
    row : pd.Series
        A row of a pd.DataFrame, over which the function can be applied.
    n_sigmas : int
        The number of standard deviations above/below the mean - used for detecting outliers
        
    Returns
    -------
    0/1 : int
        An integer with 1 indicating an outlier and 0 otherwise.
    '''
    x = row['simple_rtn']
    mu = row['mean']
    sigma = row['std']
    
    if (x > mu + n_sigmas * sigma) | (x < mu - n_sigmas * sigma):
        return 1
    else:
        return 0

**Comment by erykml** [comment]
Nice catch, I missed it! Corrected the code in the Notebook. Thanks :)
