### ISSUE TITLE
Chapter 2 backtrader_sma_strategy_optimization.py may raise error if run directly in the terminal

### ISSUE THREAD

**Issue by TY-Cheng** [erykml/Python-for-Finance-Cookbook#6]
Since in this script multiple processes are used.
![image](https://user-images.githubusercontent.com/14033617/107142668-7927ca00-696b-11eb-8179-54095358e0f0.png)

https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing

we can add one line to solve this.

if __name__ == '__main__':    
	cerebro.optstrategy(SmaStrategy, ma_period=range(10, 31))
	cerebro.broker.setcash(1000.0)
	cerebro.run(maxcpus=4)

![image](https://user-images.githubusercontent.com/14033617/107142630-51d0fd00-696b-11eb-8b7e-e22ab0e56e6d.png)

Now works well!

**Comment by erykml** [comment]
Good point! Thanks for raising this, as the code was not tested on a Windows machine.
