### ISSUE TITLE
Page 112: KeyError: 'damping_slope'

### ISSUE THREAD

**Issue by atomicatheist** [erykml/Python-for-Finance-Cookbook#7]
Code snippet from my Jupyter notebook (with my fix commented out)

phi = hw_2.model.params['damping_slope'] # fails 8/8/2021 KeyError: 'damping_slope'
#phi = hw_2.model.params['damping_trend'] # try 'damping_trend'
plot_label = f'Seasonal Smoothing (damped with $\phi={phi:.4f}$)'

Resulting error

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-814b45c1491a> in <module>
      8                    label='Seasonal Smoothing')
      9 
---> 10 phi = hw_2.model.params['damping_slope'] # fails 8/8/2021 KeyError: 'damping_slope'
     11 #phi = hw_2.model.params['damping_trend'] # try 'damping_trend'
     12 plot_label = f'Seasonal Smoothing (damped with $\phi={phi:.4f}$)'

KeyError: 'damping_slope'

Uncomment my fix, changing key 'damping_slope' to 'damping_trend', and the code runs.

**Comment by erykml** [comment]
Hi! Indeed there seemed to have been a change in the `statsmodels` API and they changed the name of the argument. Good catch! I will fix it in the upcoming second edition :)
